<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thng tin bt buc</name>
   <tag></tag>
   <elementGuidId>94d36a81-8914-4666-8beb-c139f2093ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tooltip-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tooltip516986']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f67e78c-e6e3-4633-8367-612c07d0c6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip-inner</value>
      <webElementGuid>a173d92b-3159-4b37-8d2d-1b33a287bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin bắt buộc</value>
      <webElementGuid>8f6bd29e-226d-4522-a56c-be181e1d4b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tooltip516986&quot;)/div[@class=&quot;tooltip-inner&quot;]</value>
      <webElementGuid>c0a2723b-70bd-4030-82c7-0b83cc008df8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tooltip516986']/div[2]</value>
      <webElementGuid>62a5be68-d219-4b9f-bf20-9c6058d19f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>90c1bcb2-d977-4008-990a-d6bf7635fd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin bắt buộc']/parent::*</value>
      <webElementGuid>f9dd6a06-35c6-42f4-9d9e-ba1cf4c7b4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>1d796e1e-ce82-4fcb-ae20-8c38bb739cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin bắt buộc' or . = 'Thông tin bắt buộc')]</value>
      <webElementGuid>d486456e-c38f-48c0-8eee-2d06bd785fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
