<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-icon-user-bao-loi</name>
   <tag></tag>
   <elementGuidId>32168efa-b330-4a03-bdd1-dc4299c1a069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ace-icon.fa.fa-exclamation-triangle.tooltip-error.red.show-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>023b0e8c-9c81-4da3-8477-08d6b8de72b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ace-icon fa fa-exclamation-triangle tooltip-error red show-error</value>
      <webElementGuid>1c7a06cb-6a1b-4135-bc86-45290090ae93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>29dffd7a-fc63-4048-91c7-de9f3e490c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>981d08a0-d0e9-4883-bc60-7ed0f2c967ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rel</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>b0743695-4c4c-46ef-b16f-33c96ee5654c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-custom-class</name>
      <type>Main</type>
      <value>red-tooltip</value>
      <webElementGuid>f29af162-e318-4d49-8e71-384a636b8b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Thông tin bắt buộc</value>
      <webElementGuid>20968acf-e7e5-4062-8985-81ff3fc8ece0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip497084</value>
      <webElementGuid>6574ff3c-a78e-4b00-82b5-d0af51f7df79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-skin ls-ff-sf&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-login-box&quot;]/div[@class=&quot;page-login-widget animated fadeInRight&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;ui-form-group&quot;]/error-messages[1]/i[@class=&quot;ace-icon fa fa-exclamation-triangle tooltip-error red show-error&quot;]</value>
      <webElementGuid>f3cfbf24-3ae1-4113-a66b-42fdc925cd42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>86ef1c16-2189-43a4-9415-6d6a88b9f805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
