<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-icon-pass-bao-loi</name>
   <tag></tag>
   <elementGuidId>653db5b4-0027-4322-b944-147eee1b00c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ace-icon.fa.fa-exclamation-triangle.tooltip-error.red.show-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/error-messages/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2b496e9f-ec03-4d65-b631-27b60a79bb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ace-icon fa fa-exclamation-triangle tooltip-error red show-error</value>
      <webElementGuid>1b251227-00a7-4dac-8243-cfe6317e4389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>aee1ebe0-82b1-4ca5-b010-88e91e7cba49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f8e4d5f9-d48d-41d3-b0d5-dd611d289510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rel</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>6473b61a-cbcc-4dea-80c3-fad79c303394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-custom-class</name>
      <type>Main</type>
      <value>red-tooltip</value>
      <webElementGuid>ec006666-22f8-4eee-90e5-dec8ed534c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Thông tin bắt buộc</value>
      <webElementGuid>55a133aa-3a91-4adc-9c88-2d78d6635c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip75034</value>
      <webElementGuid>ea711c8c-4f2e-4156-b4f1-3f7108b887db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-skin ls-ff-sf&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-login-box&quot;]/div[@class=&quot;page-login-widget animated fadeInRight&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;ui-form-group&quot;]/error-messages[1]/i[@class=&quot;ace-icon fa fa-exclamation-triangle tooltip-error red show-error&quot;]</value>
      <webElementGuid>eb1e5564-48ad-4631-9207-067c2e3bf004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/error-messages/i</value>
      <webElementGuid>963906e5-9233-4b6c-9433-836d2fcfad35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
