<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-TB-Mat-khau-khong-chinh-xac</name>
   <tag></tag>
   <elementGuidId>e265e46c-f901-4e93-b1f5-fe7481a404ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content_notice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='note_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41d9d064-b2fa-408d-807b-e1f34c2d9971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_notice</value>
      <webElementGuid>c3863810-3bf9-4a5b-b7ce-dc2858f671dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Mật khẩu không chính xác</value>
      <webElementGuid>d5cab4b0-d75c-4d7b-b322-13359815a8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_0&quot;)/div[@class=&quot;content_notice&quot;]</value>
      <webElementGuid>e09ff499-cab3-4358-a8ba-5f49ad91f668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='note_0']/div</value>
      <webElementGuid>cc176be8-1887-4727-a6ab-af46f90d56dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::div[2]</value>
      <webElementGuid>d50ea0cd-5477-4eb2-883b-07de276f3314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🐶 🐱 LỖI LỖI LỖI: 🐷 🐔']/parent::*</value>
      <webElementGuid>d85591df-e1ad-4592-af3d-13ac48c8237c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div</value>
      <webElementGuid>7b598d3e-9ae8-44a1-b6e2-931b508ad83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Mật khẩu không chính xác' or . = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Mật khẩu không chính xác')]</value>
      <webElementGuid>d13e8f33-78c8-42b4-9717-be67b5752309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
