<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-TB-Ten-dang-nhap-khong-ton-tai</name>
   <tag></tag>
   <elementGuidId>c5545775-8695-485f-9842-3e3f68c86e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content_notice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='note_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5f43c2c-5c0b-43b4-b41c-3495c7ef7c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_notice</value>
      <webElementGuid>b355f7c3-4d64-40b4-8b33-65d0ead80adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tên đăng nhập không tồn tại</value>
      <webElementGuid>ab94a169-b632-4428-911f-05383dd2840f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_0&quot;)/div[@class=&quot;content_notice&quot;]</value>
      <webElementGuid>d574aacb-9d04-49ba-a8b7-dfdef243394a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='note_0']/div</value>
      <webElementGuid>522cef23-e556-43ce-b0d5-fc8720aa634f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::div[2]</value>
      <webElementGuid>a555f40d-cb7d-4bc0-9048-8f07ab6aa802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🐶 🐱 LỖI LỖI LỖI: 🐷 🐔']/parent::*</value>
      <webElementGuid>5e29d8b4-c785-480f-be67-9fc2e15ad86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div</value>
      <webElementGuid>98d224d8-e878-450a-a564-8a4b44910909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tên đăng nhập không tồn tại' or . = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tên đăng nhập không tồn tại')]</value>
      <webElementGuid>40dc128b-fcdb-463e-b2b4-26e24d398182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
