<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-TB-Tai-khoan-bi-khoa</name>
   <tag></tag>
   <elementGuidId>0d29f69b-0927-451e-bed9-6ba398923745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content_notice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='note_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2937400a-a1cb-40e3-b897-ff419d8be073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_notice</value>
      <webElementGuid>799448fd-e2ba-4c85-9a63-bd4b1e031c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tài khoản đã bị khóa</value>
      <webElementGuid>42a432a6-11f0-4dae-97b5-99ec134687b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_0&quot;)/div[@class=&quot;content_notice&quot;]</value>
      <webElementGuid>405eaaed-a92d-4c86-8f52-641bd97f098f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='note_0']/div</value>
      <webElementGuid>91bb31b4-4c5d-431a-9fc9-67c1ca709e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::div[2]</value>
      <webElementGuid>700e4ba0-1581-4f71-b664-de4be1fbfdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🐶 🐱 LỖI LỖI LỖI: 🐷 🐔']/parent::*</value>
      <webElementGuid>f39dc240-c014-44e3-942e-c3dfbbd88f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div</value>
      <webElementGuid>8bb99837-ac9b-44f1-875d-3c4eabb839c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tài khoản đã bị khóa' or . = '🐶 🐱 LỖI LỖI LỖI: 🐷 🐔  Tài khoản đã bị khóa')]</value>
      <webElementGuid>99ed3884-0864-4827-ad0d-b9459d2d3c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
