<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-TB-user-Thong-tin-bat-buoc</name>
   <tag></tag>
   <elementGuidId>6e48e281-b141-444c-ba17-77d6814c1888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tooltip-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tooltip161867']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26704385-faeb-4c1e-ab60-49e365ad8e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip-inner</value>
      <webElementGuid>08ed2461-6a18-490a-99e5-234f07dd5649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin bắt buộc</value>
      <webElementGuid>b1825995-52d2-4041-b02a-b5b3353f2caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tooltip161867&quot;)/div[@class=&quot;tooltip-inner&quot;]</value>
      <webElementGuid>7fe43187-c57c-49f5-85aa-96dc25cc4553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tooltip161867']/div[2]</value>
      <webElementGuid>a653eadf-b022-4c7c-b892-c067905cd9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::div[3]</value>
      <webElementGuid>172388dc-8a5f-4865-9f04-fe13490b688a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin bắt buộc']/parent::*</value>
      <webElementGuid>635e4c48-95c3-4755-9316-1cc5c8e3ee29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>6c29475d-c14a-4984-aca0-4e4a9a5c15a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin bắt buộc' or . = 'Thông tin bắt buộc')]</value>
      <webElementGuid>2a533cb6-9f54-451c-b7de-fde69f53e8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
