<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login-TB-loi-user</name>
   <tag></tag>
   <elementGuidId>50657d90-a6b6-4e29-a7de-1602ba8cde60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tooltip-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tooltip257974']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60a61e0f-fb18-4350-b26b-616de6091178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip-inner</value>
      <webElementGuid>1407ee76-dcc6-43fc-889d-55c1d5e74d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin bắt buộc</value>
      <webElementGuid>f84807db-8367-4486-8366-c16112d64d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tooltip257974&quot;)/div[@class=&quot;tooltip-inner&quot;]</value>
      <webElementGuid>85a26649-334b-4c4f-a30a-e30df578abbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tooltip257974']/div[2]</value>
      <webElementGuid>0b44e065-93f8-4d58-aa04-c562a62c42c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::div[3]</value>
      <webElementGuid>871f875c-a35b-4ae5-bca8-c9983e1ada5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin bắt buộc']/parent::*</value>
      <webElementGuid>f8eeb63b-faf1-4886-9ef6-d82538c85405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>5338dc6b-d9b2-4e3c-9581-b5bcb1084a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin bắt buộc' or . = 'Thông tin bắt buộc')]</value>
      <webElementGuid>743a5714-a601-4193-9038-d3c4c4c6aaf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
