<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngy sinh_ng-tns-c7-7 ui-inputtext ui-_9567e1</name>
   <tag></tag>
   <elementGuidId>bcea9e0c-47dd-4850-9cc2-9a49c48d4420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c7-7.ui-inputtext.ui-widget.ui-state-default.ui-corner-all.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dffcf302-8c03-456b-ba2a-2438e09c3981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4727ba5-348b-4cbf-84cf-3fe183a065c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58913828-3978-4c82-ba40-0062f4882891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c7-7 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>066d307d-d408-4a15-9699-ea867660a762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>ui-inputtext ui-widget ui-stat</value>
      <webElementGuid>958e1a65-5b6d-4345-9f87-408400926e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-0-content&quot;)/div[@class=&quot;ui-panel-content ui-widget-content&quot;]/form[@class=&quot;ng-untouched ng-dirty ng-valid ng-star-inserted&quot;]/div[@class=&quot;ui-g lap-form&quot;]/div[@class=&quot;ui-g-12&quot;]/div[@class=&quot;ui-g-12 ui-form-group&quot;]/div[@class=&quot;ui-g-12 ui-md-4&quot;]/p-calendar[@class=&quot;ng-tns-c7-7 ui-inputwrapper-filled ng-untouched ng-valid ui-inputwrapper-focus ng-dirty&quot;]/span[@class=&quot;ng-tns-c7-7 ui-calendar ui-calendar-w-btn&quot;]/input[@class=&quot;ng-tns-c7-7 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted&quot;]</value>
      <webElementGuid>8540b12f-0970-4d42-bd1f-a1961cd9b533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>7bc8ee90-350e-4d89-ad10-fe0e98e43824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-0-content']/div/form/div/div/div[3]/div[2]/p-calendar/span/input</value>
      <webElementGuid>0fc571da-ab44-48dd-922a-ec0cc265b5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>aa6087f1-9b95-40d4-a404-a8d0bd21c5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d25cf446-51e4-482c-9253-0f46794776c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
