<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TTCN-TB-thanh-cong</name>
   <tag></tag>
   <elementGuidId>d44146e0-ec37-4fe6-82ad-93d6852f57e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content_notice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='note_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3b6482c-e5a1-4515-9b8f-9912f8136d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_notice</value>
      <webElementGuid>0a645aaa-be6c-498a-a074-c35f799a66e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🐶 🐱 XONG =)): 🐷 🐔  Cập nhật thành công</value>
      <webElementGuid>94a6df8b-3b3d-44d9-a0b0-0de2570f3bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_0&quot;)/div[@class=&quot;content_notice&quot;]</value>
      <webElementGuid>16437c7e-6b4e-4536-8ebe-4d95ebb5e522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='note_0']/div</value>
      <webElementGuid>9982bb80-df19-4f9d-9aac-23283df2c109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khác'])[1]/following::div[2]</value>
      <webElementGuid>b09d6c03-0f2a-4dca-a8b7-672c96ff7db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nữ'])[3]/following::div[3]</value>
      <webElementGuid>a61d6b66-b0bb-4cf0-9106-7e8f8616932a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🐶 🐱 XONG =)): 🐷 🐔']/parent::*</value>
      <webElementGuid>f61e04a1-464d-4490-8baf-01d08b23c52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>2157245d-f965-4e96-be92-833d38cdda7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '🐶 🐱 XONG =)): 🐷 🐔  Cập nhật thành công' or . = '🐶 🐱 XONG =)): 🐷 🐔  Cập nhật thành công')]</value>
      <webElementGuid>b197eb6c-4d11-42d8-b526-ffd1041dc882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
