<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thoat</name>
   <tag></tag>
   <elementGuidId>323fd7ca-c3e8-4ad3-bbf9-e71c9c83b47c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.btn-sm.btn-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c51a8614-9f62-4655-9126-211e541e3fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm btn-close</value>
      <webElementGuid>3b2b348a-02c4-4a5e-8d71-0f044016f2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edce6a94-420f-44d6-a652-0f489ba1acfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
             Thoát
          </value>
      <webElementGuid>f4b0daf7-74c3-4000-99ef-d05760cf4a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateGraduationProjectProcessRefModal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content ng-star-inserted&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-default btn-sm btn-close&quot;]</value>
      <webElementGuid>7c72a9ab-103e-4f6d-81a3-55249128ea7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>b2e6c33e-b701-4fe5-99e1-0db7ca0acd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateGraduationProjectProcessRefModal']/div/div/div[2]/button</value>
      <webElementGuid>aeb5683f-8f1e-4b0f-83f0-c770529646ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoàn thiện các thủ tục sau bảo vệ'])[1]/following::button[1]</value>
      <webElementGuid>542fa1ed-4f88-40e4-b73d-60a0540cec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thoát']/parent::*</value>
      <webElementGuid>84bd12b5-a727-4be7-aeb2-e35123540433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/button</value>
      <webElementGuid>146c7e5e-081a-4ac4-98a1-9e8687ab9dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
             Thoát
          ' or . = '
             Thoát
          ')]</value>
      <webElementGuid>b4cdd52f-52ef-4cc6-9a92-1353c39c1e9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
