<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_Luu_thanh_cong</name>
   <tag></tag>
   <elementGuidId>c2554ab0-8334-4453-912d-cb0ee1934b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='note_0']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content_notice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80b6de28-fc1c-4bdc-99ef-01666c7ba4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_notice</value>
      <webElementGuid>67fc48a0-0db1-440e-b5ea-9a2ff1f13f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🐶 🐱 XONG =)): 🐷 🐔  Bạn báo cáo thành công</value>
      <webElementGuid>8583ae5e-9823-4221-bc88-f54e8e5c87fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_0&quot;)/div[@class=&quot;content_notice&quot;]</value>
      <webElementGuid>afa61f02-5827-4633-915a-5b3e5f56fda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='note_0']/div</value>
      <webElementGuid>674361cd-01e2-48c8-82e4-b13982510bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị bản ghi từ 1 đến 10 trên tổng số 20'])[1]/following::div[16]</value>
      <webElementGuid>f61e9342-2215-45c6-92ca-b247e6a41e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🐶 🐱 XONG =)): 🐷 🐔']/parent::*</value>
      <webElementGuid>76224048-0be2-4dc5-a933-3750a7f194b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>4e2e17e3-871f-4633-b6e5-40c552f86f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '🐶 🐱 XONG =)): 🐷 🐔  Bạn báo cáo thành công' or . = '🐶 🐱 XONG =)): 🐷 🐔  Bạn báo cáo thành công')]</value>
      <webElementGuid>6553974d-b62d-4bba-9b71-76704e4d73e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
